name: Testing Deployment to AWS
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    environment: Dev
    
    steps:   
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
              mkdir ~/GHA_dir
            # cd /var/www/my-app
            # git pull origin main
            # npm install
            # pm2 restart my-app
